FROM alpine:3.21

LABEL maintainer "JesusDF"

RUN mkdir -p /app \
        && apk add --no-cache openjdk11-jre msttcorefonts-installer fontconfig \
        && update-ms-fonts \
        && fc-cache -f \
        && ln -s /usr/share/fonts/truetype/msttcorefonts /usr/lib/jvm/default-jvm/jre/lib/fonts \
        && adduser -D crystal
WORKDIR /app
COPY CrystalCmd.jar /app/

EXPOSE 4321
USER crystal
CMD ["java", "-jar", "/app/CrystalCmd.jar"]
