name: Docker Image CI

on:
  push:
    branches: [ "master" ]
    tags: [ "v*" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
         username: ${{ secrets.DOCKER_HUB_USERNAME }}
         password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Last commit
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Build and push - alpine
        uses: docker/build-push-action@v3
        with:
          context: ./docker
          file: ./docker/Dockerfile.alpine
          platforms: linux/amd64
          push: true
          tags: |
            docker.io/${{ github.repository_owner }}/crystalcmd:stable
            docker.io/${{ github.repository_owner }}/crystalcmd:${{ steps.vars.outputs.sha_short }}
      #- name: Build and push - ubuntu
      #  uses: docker/build-push-action@v3
      #  with:
      #    context: ./docker
      #    file: ./docker/Dockerfile
      #    platforms: linux/amd64
      #    push: true
      #    tags: |
      #      docker.io/${{ github.repository_owner }}/crystalcmd:ubuntu-stable
      #      docker.io/${{ github.repository_owner }}/crystalcmd:u-${{ steps.vars.outputs.sha_short }}
      - name: Update Docker Hub Description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          repository: ${{ github.repository_owner }}/crystalcmd
          readme-filepath: ./Readme.md
