name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  windows-build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.1
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Build
      run: choco install CrystalReports2010Runtime -y && cd dotnet && ./build_zips.ps1
    - name: Archive artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-output
        path: |
          dotnet/build
        retention-days: 1
